config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :users, only: %i[new create edit update destroy]
  devise_for :users

  # dashboard user_managment
  # config/routes.rb
  resources :users do
    member do
      post 'reset_password'
    end
  end

  namespace :admin do
    resources :user_managment, only: [:index] do
      member do
        get 'new_user', to: 'user_managment#new_user', as: :user_managment_new_user
        get 'create_user', to: 'user_managment#create_user', as: :user_managment_create_user
        get 'edit_user/:id', to: 'user_managment#edit_user', as: :user_managment_edit_user
        get 'delete_user/:id', to: 'user_managment#delete_user', as: :user_managment_delete_user
      end
    end
    get 'manage_user', to: 'user_managment#manage_user', as: :manage_user
  end

  
  resources :addresses
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/admin/user_managment_controller.rb
# app/controllers/user_managment_controller.rb
class Admin::UserManagmentController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin!
  before_action :set_user, only: %i[edit_user delete_user]

  def index
  end

  def manage_user
    # @users = User.where(role: :client)
    @users = User.all 
    @roles = @users.pluck(:role).uniq
  end

  def new_user
    @user = User.new
  end

  def create_user
    @user = User.new(user_params)
    if @user.save
      redirect_to user_managment_path, notice: 'User created successfully.'
    else
      render :new
    end
  end

  def delete_user
    @user.transaction do
      @user.destroy
    end
    redirect_to user_managment_path, success: 'Compte supprimé'
  end

  def edit_user
  end

  private

  def authorize_admin!
    authorize! :manage, :all
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/user_managment/admin_account.html.erb
<% if flash[:danger] %>
  <div class="alert alert-danger">
    <%= flash[:danger] %>
  </div>
<% end %>

<div style="text-align: center;">
  <img src="<%= asset_path('Logo.png') %>" alt="Image" style="width: 100px; height: 100px; margin-right: 10px;">
  <h1>Liste des Utilisateurs Leobotics</h1>
</div>


<a href="<%= new_user_path %>" class="btnPage btn-dashboard btn-new" id="showAccountForm">
  <i class="fa fa-plus" aria-hidden="true"></i>
</a>
<div class="table-responsive">
  <div style="width: 100%; height: 750px; overflow-y: auto;">
    <div class="datatable-container">
      <table id="admin_data" align="center" border="2" cellpadding="2" cellspacing="4" width=auto>
        <thead>
          <tr>
            <th>Email</th>
            <th>Nom d'utilisateur</th>
            <td><select id="role-filter"><option value="">Rôles</option></select></td>
            <th>Prénom</th>
            <th>Nom de famille</th>
            <th>Numéro de téléphone</th>
            <th>Adresses</th>
            <th><select id="city-filter"><option value="">Villes</option></select></th>
            <th><select id="country-filter"><option value="">Pays</option></select></th>
            <th><select id="pc-filter"><option value="">CP</option></select></th>
            <th>Historique des commandes</th>
            <th>Nombre de commandes</th>
            <th>Dernière connexion</th>
            <th>Date de création du compte</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |u|%>
          <tr data-href-edit="<%= url_for(edit_account_path(u.account)) %>" data-href="<%= url_for(account_path(u.account)) %>">
            <td><%= u.email %></td>
            <td><%= u.username %></td>
            <td><%= u.role %></td>     
            <td><%= u.account.firstname %></td>
            <td><%= u.account.lastname %></td>
            <td><%= u.account.phone_number %></td>
            <td>
              <% if u.account.addresses.first.present? %>
                <%= u.account.addresses.first.street %>  
              <% else %>
                  Pas de rue disponible
              <% end %>
            </td>
            <td>
              <% if u.account.addresses.first.present? %>
                <%= u.account.addresses.first.city %>  
              <% else %>
                  Pas de ville disponible
              <% end %>
            </td>
            <td>
              <% if u.account.addresses.first.present? %>
                <%= u.account.addresses.first.state %>  
              <% else %>
                  Pas d'état disponible
              <% end %>
            </td>
            <td>
              <% if u.account.addresses.first.present? %>
                <%= u.account.addresses.first.pc %>  
              <% else %>
                  Pas de code postal disponible
              <% end %>
            </td>
            <td></td>
            <td></td>
            <td> <% if u.current_sign_in_at.present? %> <%= u.current_sign_in_at.strftime('%Y-%m-%d %H:%M:%S') %> <% else %> Jamais connecté <% end %> </td>
            <td><%= u.account.created_at.strftime('%Y-%m-%d') %></td>

            <td align="center" class="btns dsh-csv">
              <div class="btnPage">
                <a href="<%= edit_account_path(u.account) %>" class="btnPage btn-dashboard btn-edit">
                  <i class="fa fa-pencil" aria-hidden="true"></i>
                </a>
              </div>    
              <div class="btnPage">
              <%= button_to user_path(u), method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?' }, class: "btndestroy link-style", style: "border: none;" do %>
                <i class="fa-solid fa-trash"></i>
              <% end %>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<style>
  .link-style {
    color: blue; 
    text-decoration: underline; 
    background-color: transparent; 
    border: none; 
    cursor: pointer;
  }
  tr[data-href] {
    cursor: pointer;
  }

  tr[data-href]:hover {
    background-color: lightgray;
  }

  body {
    background-color: #446084;
  }


  #admin_data {
    background-color: #C0B3B3;
    height: calc(100vh - 40px); /* Réduire la hauteur en fonction de la marge */
    overflow: hidden; /* Masque le débordement */
    
  }


  .datatable-container {
    margin: 20px;
    border: 1px solid #446084; /* Bordure autour de la DataTable */
    border-radius: 10px; /* Rayon des coins de la bordure (arrondi) */
    padding: 10px; /* Espacement à l'intérieur de la bordure */
    background-color: #C0B3B3; /* Couleur de fond du conteneur */
    height: calc(100% - 40px); /* Réduire la hauteur en fonction de la marge */
    overflow: auto; 
  }

  .btn-new {
    font-size: 24px; 
    padding: 10px 20px; 
    margin-right: 10px;
  }

  .btn-edit {
    font-size: 24px;
    padding: 10px 20px; 
    margin-right: 10px;
  }

  .btndestroy {
    font-size: 24px;
    padding: 10px 20px; 
    margin-right: 10px;
  }

</style>

<script>
  console.log("fahadi");
  $(document).ready(function () {
    var table = $("#admin_data").DataTable({
      select: {
        style: "single",
      },
      scrollX: true
      
    });

    // Remplissez la liste déroulante avec les rôles uniques existants
    table
      .column(2)
      .data()
      .unique()
      .sort()
      .each(function (d, j) {
        $("#role-filter").append('<option value="' + d + '">' + d + "</option>");
      });

    // Écoutez les changements de sélection dans la liste déroulante
    $("#role-filter").on("change", function () {
      var selectedRole = $(this).val();
      table.column(2).search(selectedRole).draw();
    });
  

    // Remplissez la liste déroulante des adresses avec des valeurs uniques
    table
      .column(7)
      .data()
      .unique()
      .sort()
      .each(function (d, j) {
        $("#city-filter").append('<option value="' + d + '">' + d + "</option>");
      });

    // Écoutez les changements de sélection dans la liste déroulante d'adresse
    $("#city-filter").on("change", function () {
      var selectedAddress = $(this).val();
      table.column(7).search(selectedAddress).draw();
    });

    // Remplissez la liste déroulante des adresses avec des valeurs uniques
    table
      .column(8)
      .data()
      .unique()
      .sort()
      .each(function (d, j) {
        $("#country-filter").append('<option value="' + d + '">' + d + "</option>");
      });

    // Écoutez les changements de sélection dans la liste déroulante d'adresse
    $("#country-filter").on("change", function () {
      var selectedAddress = $(this).val();
      table.column(8).search(selectedAddress).draw();
    });

    // Remplissez la liste déroulante des adresses avec des valeurs uniques
    table
      .column(9)
      .data()
      .unique()
      .sort()
      .each(function (d, j) {
        $("#pc-filter").append('<option value="' + d + '">' + d + "</option>");
      });

    // Écoutez les changements de sélection dans la liste déroulante d'adresse
    $("#pc-filter").on("change", function () {
      var selectedAddress = $(this).val();
      table.column(9).search(selectedAddress).draw();
    });
  
  });

</script>

<script>
  console.log("fahadi");
  $(document).ready(function() {
    
    $(".btndestroy").on("click", function(e) {
      var confirmationMessage = $(this).data("confirm");
      
      if (!confirm(confirmationMessage)) {
        e.preventDefault();
      }
    });
  });
</script>


<script>
  $(document).on('click', '.btnPage.btn-dashboard.btn-new', function(e) {
    e.preventDefault();
    shownewAccountForm();
  });

  function shownewAccountForm() {
    $.ajax({
      type: 'GET',
      url: '<%= j new_user_path %>', // Assurez-vous d'utiliser la méthode "j" pour échapper correctement l'URL
      dataType: 'html',
      success: function(response) {
        dispayNewAccount(response);
      },
      error: function(jqXHR, textStatus, errorThrown) {
        console.error('Error fetching data:', textStatus, errorThrown, jqXHR.responseText);
      }
    });
  }

  function dispayNewAccount(data) {
    Swal.fire({
      title: 'Nouveau compte utilisateur',
      html: data, 
      showCloseButton: true,
      customClass: {
        denyButton: 'edit-imprimante-btn',
      },
      width: '800px', // Vous pouvez personnaliser la largeur ici
      
    }).then((result) => {
      // Gérez les actions de l'utilisateur après avoir affiché le formulaire
      if (result.isDenied) {
        // Gérez le clic sur le bouton "Modifier" ici
      }
    });
  }
</script>


<script>
  document.addEventListener('DOMContentLoaded', function() {
    const tableRows = document.querySelectorAll('tr[data-href]');

    tableRows.forEach(function(row) {
      row.addEventListener('dblclick', function() {
        const url = this.getAttribute('data-href');

        fetchAndDisplayData(url);
      });
    });

    function fetchAndDisplayData(url) {
      fetch(url)
        .then(response => response.text())
        .then(html => {
          displayData(html);
        })
        .catch(error => {
          console.error('Error fetching data:', error);
        });
    }

    function displayData(html) {
      Swal.fire({
        title: 'Détails de l\'Utilisateur',
        html: html, // Affichez le contenu HTML récupéré
        showCloseButton: true,
        backdrop: 'rgba(0, 0, 0, 0.5)'
      });
    }
  });
</script>



<script>
  document.addEventListener('DOMContentLoaded', function() {
    const editLinks = document.querySelectorAll('tr[data-href-edit] .btnPage.btn-dashboard.btn-edit');

    editLinks.forEach(function(link) {
      link.addEventListener('click', function(e) {
        e.preventDefault(); // Annuler le comportement par défaut du lien
        const url = this.getAttribute('href'); // Obtenir l'URL du lien

        EditData(url);
      });
    });

    function EditData(url) {
      fetch(url)
        .then(response => response.text())
        .then(html => {
          showeditData(html);
        })
        .catch(error => {
          console.error('Error fetching data:', error);
        });
    }

    function showeditData(html) {
      Swal.fire({
        title: 'Modifier l\'Utilisateur',
        html: html,
        showCloseButton: true,
        customClass: {
          popup: 'custom-popup-class',
      },
      }).then((result) => {
        if (result.isDenied) {
          // Gérer le clic sur le bouton "Modifier" ici
        }
      });
    }
  });
</script>

app/views/user_managment/index.html.erb
<h1>Dashboard ADMIN</h1>

<button type="button" class="btn-item"><a class="nav-item" href="<%= admin_manage_user_path %>">Gestion de l'équipe Leobotics</a></button>