config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :users, only: %i[new create edit update destroy]
  devise_for :users

  # dashboard user_managment
  # config/routes.rb
  resources :users do
    member do
      post 'reset_password'
    end
  end

  namespace :admin do
    resources :user_managment, only: [:index] do
      member do
        get 'new_user', to: 'user_managment#new_user', as: :user_managment_new_user
        get 'create_user', to: 'user_managment#create_user', as: :user_managment_create_user
        get 'edit_user/:id', to: 'user_managment#edit_user', as: :user_managment_edit_user
        get 'delete_user/:id', to: 'user_managment#delete_user', as: :user_managment_delete_user
      end
    end
    get 'manage_user', to: 'user_managment#manage_user', as: :manage_user
  end

  
  resources :addresses
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :set_account, if: :user_signed_in?

  def index
  end

  private

    def set_account
      @account = Account.find_by(user_id: current_user.id)
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Bienvenue sur boiler plate</h1>

<div class="container">
  <h1 class="display-4">Welcome to My Rails App</h1>
  <p class="lead">This is a Bootstrap-styled page.</p>
</div>
<div class="test">
  sjkd
</div>
<% if user_signed_in? %>
<p>
    <%= link_to 'Se deconnecter', destroy_user_session_path, method: :delete %>
    <%if current_user.admin?%>
      <%= link_to 'Dashboard Admin', admin_user_managment_index_path%>
    <%end %>
    <%= link_to 'Edit information', edit_account_path(@account)%>
    
</p>

<% else %>
<p>
    <%= link_to 'Se connecter', new_user_registration_path, id: 'new-user-link' %>
</p>

<% end %>


<script>
  document.addEventListener('DOMContentLoaded', function() {
    const newUserLink = document.getElementById('new-user-link');

    if (newUserLink) {
      newUserLink.addEventListener('click', function(e) {
        e.preventDefault(); // Annuler le comportement par défaut du lien
        const url = this.getAttribute('href'); // Obtenir l'URL du lien

        showEditData(url);
      });
    }

    function showEditData(url) {
      fetch(url)
        .then(response => response.text())
        .then(html => {
          Swal.fire({
            html: html,
            showCloseButton: true,
            customClass: {
              popup: 'custom-popup-class',
            },
          }).then((result) => {
            if (result.isDenied) {
              // Gérer le clic sur le bouton "Modifier" ici
            }
          });
        })
        .catch(error => {
          console.error('Error fetching data:', error);
        });
    }
  });
</script>

app/views/home/private.html.erb
<h1>Home#private</h1>
<p>Find me in app/views/home/private.html.erb</p>