config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :users, only: %i[new create edit update destroy]
  devise_for :users

  # dashboard user_managment
  # config/routes.rb
  resources :users do
    member do
      post 'reset_password'
    end
  end

  namespace :admin do
    resources :user_managment, only: [:index] do
      member do
        get 'new_user', to: 'user_managment#new_user', as: :user_managment_new_user
        get 'create_user', to: 'user_managment#create_user', as: :user_managment_create_user
        get 'edit_user/:id', to: 'user_managment#edit_user', as: :user_managment_edit_user
        get 'delete_user/:id', to: 'user_managment#delete_user', as: :user_managment_delete_user
      end
    end
    get 'manage_user', to: 'user_managment#manage_user', as: :manage_user
  end

  
  resources :addresses
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user
    has_one_attached :image, dependent: :destroy
    has_many :addresses, dependent: :destroy

    # validates :phone_number, format: { with: /\A(06|07)\d{8}\z/, message: "The phone number must start with 06 or 07 and have 10 digits in total" }

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :set_account, only: %i[ show edit update destroy ]



  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
    @user = User.find(params[:id])
    @account = Account.find(params[:id])
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
    @user = @account.user
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update


    @account = Account.find(params[:id])
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      if user_signed_in?
        @account = Account.find_by(user_id: current_user.id)
        puts "Account===: #{@account}"
      end
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:firstname, :lastname, :phone_number, :image)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <div class="dsh-form">
    <p><strong>Nom d'utilisateur :</strong> <%= @user.username %></p>
    <p><strong>Email :</strong> <%= @user.email %></p>
    <p><strong>Rôle :</strong> <%= @user.role.humanize %></p>
  </div>

  <div class="dsh-form">
    <p><strong>Image de Profil :</strong></p><%= image_tag @account.image.url, width: '100', height: '100' if @account.image.present? %>
    <p><strong>Prénom :</strong> <%= @account.firstname %></p>
    <p><strong>Nom de Famille :</strong> <%= @account.lastname %></p>
    <p><strong>Numéro de Téléphone :</strong> <%= @account.phone_number %></p>
    <p><strong>Adresses :</strong></p>
    <ul>
      <% @account.addresses.each_with_index do |address, index| %>
        <strong>Adresse <%= index + 1 %>:</strong>
        <ul>
          <li><strong>Rue :</strong> <%= address.street %></li>
          <li><strong>Rue 2 :</strong> <%= address.street_two %></li>
          <li><strong>Ville :</strong> <%= address.city %></li>
          <li><strong>Pays :</strong> <%= address.country %></li>
          <li><strong>État :</strong> <%= address.state %></li>
          <li><strong>Code Postal :</strong> <%= address.pc %></li>
        </ul>
      <% end %>
    </ul>
  </div>
</div>

app/views/accounts/_form.html.erb
<div class="dsh-form">
  <%= form_with(model: @user) do |form| %>
    <% if @user.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this User from being saved:</h2>
        <ul>
          <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div>
    <%= form.label :username, "Nom d'utilisateur", class: "form-label" %><br>
    <%= form.text_field :username, placeholder: "Nom d'utilisateur", class: "form-input" %><br>
    <%= form.label :email, "Email", class: "form-label" %><br>
    <%= form.text_field :email, placeholder: "Email", class: "form-input" %><br>
    <%= label_tag "chosen_role", "Rôle", class: "form-label" %><br>
    <%= select_tag "user[role]", options_for_select(User.roles.keys.map { |role| [role.humanize, role] }), prompt: "Sélectionner un rôle", class: "form-input" %>
    <%= form.label :password, "Mot de passe", class: "form-label" %>
    <%= form.password_field :password, placeholder: "Mot de passe", class: "form-input" %>
    <%= form.label :password_confirmation, "Confirmer le mot de passe", class: "form-label" %>
    <%= form.password_field :password_confirmation, placeholder: "Confirmer le mot de passe", class: "form-input" %>
  </div>

    <%= form.fields_for :account, account do |account_fields| %>
      <%= account_fields.hidden_field :id %>
      <div>
        <%= account_fields.label :'Image de profil' %>
        <%= account_fields.file_field :image %>
      </div>

      <div>
        <%= account_fields.label :'Prénom', style: "display: block" %>
        <%= account_fields.text_field :firstname %>
      </div>

      <div>
        <%= account_fields.label :'Nom de famille', style: "display: block" %>
        <%= account_fields.text_field :lastname %>
      </div>

      <div>
        <%= account_fields.label :'Numéro de téléphone', style: "display: block" %>
        <%= account_fields.text_field :phone_number %>
      </div>
    <% end %>
    <br>
    <%= form.submit %>
  <% end %>
</div>

<br>
<%= button_to "Réinitialiser le mot de passe", reset_password_user_path(@user), method: :post, class: 'btn btn-primary', data: { confirm: 'Êtes-vous sûr de vouloir réinitialiser le mot de passe de cet utilisateur ?' } %>

app/views/accounts/edit.html.erb
<%= render "form", account: @account %>

<br>

app/views/accounts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Accounts</h1>

<div id="accounts">
  <% @accounts.each do |account| %>
    <%= render account %>
    <p>
      <%= link_to "Show this account", account %>
    </p>
  <% end %>
</div>

<%= link_to "New account", new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @account %>